stages:
  - dependency_build
  - kernel_build

before_script:
  - mkdir -p "$CI_PROJECT_DIR/linux"

include:
  - local: .gitlab/templates/build_docker_ci_images.yml
  - local: .gitlab/templates/build_kernel.yml

rel32-rebase:
  extends: .build_kernel

rel32-kvm:
  extends: .build_kernel
  variables:
    KERNEL_VER: "linux-rel32-kvm"
    PATCH:      "true"
